# Your 1st Wi-Fi SSID and password
wifi_ssid:     ""
wifi_password: ""

# Your 2nd Wi-Fi SSID and password
wifi2_ssid:     ""
wifi2_password: ""

# Your 3nd Wi-Fi SSID and password
wifi3_ssid:     ""
wifi3_password: ""

# Fallback Hotspot (captive portal) in case Wi-Fi connection fails
wifiap_ssid:     ""
wifiap_password: ""

# Web Server
web_username: ""
web_password: ""

# MQTT Server
mqtt_broker: ""
mqtt_username: ""
mqtt_password: ""

# OTA Update
ota_password: ""

# ESPHome API
api_password: ""
